### ISSUE TITLE
[Feature Request] Combine login functionality into one 'Login' which will prompt modal

### ISSUE THREAD

**Issue by foreza** [jasonh117/idt-tlv#2]
**Justification:**

For most standard layout, login feature is usually presented as one unified 'Login'.
Once the user selects login, several variants could be presented:

1. Drop down for user / password entry
2. Select service for entry in drop down
3. Select service for entry in pop-up / modal
4. Redirect to login page and bring user back to index after successful auth

**Recommendation:**

1. Combine outlook login / google login into just generic 'Login' on navbar.
2. Have radio button select for 'Login with Google' or 'Login with Outlook'
3. Use modal popup and grey out background

**Comment by jasonh117** [comment]
Do you want to take on the challenge and implement this feature? 😃

**Comment by foreza** [comment]
Hi @jasonh117 

Please review my [commit](https://github.com/jasonh117/idt-tlv/commit/c40dcac46bf5f5999b69b174119a36c2af1c7dd7):

**Comment by foreza** [comment]
>:(
